//counter action types
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DOUBLE_ASYNC = 'COUNTER_DOUBLE_ASYNC'

export const UPDATE_BASE_URL = 'UPDATE_BASE_URL'
export const UPDATE_MAP_KEY = 'UPDATE_MAP_KEY'